run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-dirs:
    - x/ref/services/internal/restsigner/signer

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: unused-parameter
        disabled: true

linters:
  enable:
    - bodyclose
    - gosec
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - copyloopvar
    - staticcheck
    - typecheck
    - unconvert
    - unused
  disable-all: true
