services:
  mounttabled:
    image: mounttabled
    ports: [9001:9002]
    expose: [9002]
    command: --v23.tcp.address=:9002 --v23.virtualized.provider=aws --v23.vtrace.enable-aws-xray=true
    environment:
      - AWS_XRAY_DAEMON_ADDRESS=aws_xray_daemon:2000
    depends_on: [aws_xray_daemon]
    networks:
      aws:
        ipv4_address: 169.254.169.10
  echod1:
    image: echod
    environment:
      - V23_CREDENTIALS=/bin/creds
      - V23_NAMESPACE=/mounttabled:9002
      - AWS_XRAY_DAEMON_ADDRESS=aws_xray_daemon:2000
    ports: [10001:10001]
    depends_on: [mounttabled, aws_xray_daemon]
    command: --name=echo-server/echod1 --v23.tcp.address=:10001 --v23.virtualized.tcp.public-address=127.0.0.1:1002  --v23.virtualized.provider=aws --v23.vtrace.enable-aws-xray=true --v23.vtrace.root-span-name="echod1"
    networks:
      aws:
        ipv4_address: 169.254.169.11
  echod2:
    image: echod
    environment:
      - V23_CREDENTIALS=/bin/creds
      - V23_NAMESPACE=/mounttabled:9002
      - AWS_XRAY_DAEMON_ADDRESS=aws_xray_daemon:2000
    ports: [10002:10002]
    command: --name=echo-server/echod2 --v23.tcp.address=:10002 --v23.virtualized.tcp.public-address=127.0.0.1:1002 --v23.virtualized.provider=aws --v23.vtrace.enable-aws-xray=true  --v23.vtrace.root-span-name="echod2"
    depends_on: [mounttabled, aws_xray_daemon]
    networks:
      aws:
        ipv4_address: 169.254.169.12
  echod3:
    image: echod
    environment:
      - V23_CREDENTIALS=/bin/creds
      - V23_NAMESPACE=/mounttabled:9002
      - AWS_XRAY_DAEMON_ADDRESS=aws_xray_daemon:2000
    ports: [10003:10003]
    command: --name=echo-server/echod3 --v23.tcp.address=:10003 --v23.virtualized.tcp.public-address=127.0.0.1:10003 --v23.virtualized.provider=aws --v23.vtrace.enable-aws-xray=true  --v23.vtrace.root-span-name="echod3"
    depends_on: [mounttabled, aws_xray_daemon]
    networks:
      aws:
        ipv4_address: 169.254.169.13
  echo_client:
    image: echo
    environment:
      - V23_CREDENTIALS=/bin/creds
      - V23_NAMESPACE=/mounttabled:9002
      - AWS_XRAY_DAEMON_ADDRESS=aws_xray_daemon:2000
    ports: [10020:10020, 8000:8000]
    command: --v23.tcp.address=:10020 --v23.virtualized.tcp.public-address=127.0.0.1:1020 --v23.virtualized.provider=aws --v23.vtrace.enable-aws-xray=true  --name=echo-server/echod1 --forward-to=echo-server/echod2,echo-server/echod3,echo-server/echod1 --iterations=1 --http=":8000"
    depends_on: [echod1, echod2, echod3]
    networks:
      aws:
        ipv4_address: 169.254.169.20
  aws_metadata:
    image: amazon/amazon-ec2-metadata-mock:v1.8.1
    command: -n 169.254.169.254 -p 80
    expose: [80]
    volumes:
      - ./aes_logs:/etc/aws_logs:rw
      - ./aws_configs:/etc/aws_configs:ro
    networks:
      aws:
        ipv4_address: 169.254.169.254
  aws_xray_daemon:
    image: amazon/aws-xray-daemon:latest
    command: -c /etc/aws_configs/xray_daemon.yml
    ports: [2000:2000/tcp, 2000:2000/udp]
    expose: [2000/tcp, 2000/udp]
    volumes:
      - ./aws_logs:/etc/aws_logs:rw
      - ./aws_configs:/etc/aws_configs:ro
      - aws_creds:/home/xray/.aws:ro
    networks:
      aws:
        ipv4_address: 169.254.169.200

volumes:
  aws_logs:
    driver: local
  aws_configs:
    driver: local
  aws_creds:
    driver: local
    driver_opts:
      type: none
      device: ./xray_aws_creds
      o: bind

networks:
  aws:
    ipam:
      driver: default
      config:
        - subnet: "169.254.169.0/24"
          gateway: 169.254.169.1
